#Site settings
title: Myp Blog
SEOTitle: Mya blog | Myp Blog 
header-img: images/huanhuan.jpg
#email:13102722298@163.com
#description:"headache"
#keyword:"a,b,c,d,email"
#url:"https://victoriaalison.github.io/"
#baseurl:""

#Sidebar settings
sidebar:true
sidebar-about-description:"emmmmmmm"
sidebar-avatar:/images/huanhuan.jpg
